### ISSUE TITLE
not working well with empty tableview

### ISSUE THREAD

**Issue by simpzan** [litl/WKVerticalScrollBar#3]
when working with tableview,
if the tableview is empty, the scroll bar should hide, but it shows, and when I drag it, the tableview flashes a lot.
if the tableview is not full of a screen of data. and when I drag it, it flashes a lot as well.

**Comment by btaylor-litl** [comment]
Thanks for your bug report.  I fixed the empty table view case in 1935442 by hiding the scroll bar when there is no content to scroll, but I can't seem to reproduce any flashing.  Can you share the application that you've embedded WKVerticalScrollBar in, or perhaps provide more information?  What device are you using?

**Comment by simpzan** [comment]
the scroll bar is hide, but the interaction is still there. if you pan on the scroll bar area, the tableview will flash.
I think you can fix it just by disable the interaction when the scroll bar is hidden. and enable interaction when the scroll bar shows.

**Comment by btaylor-litl** [comment]
Ah, I see what you're talking about now.  I'll have a fix in a minute.
